### ISSUE TITLE
munge/sqlite seems to apply implicit DISTINCT clause on SELECT statement 

### ISSUE THREAD

**Issue by fvanzeveren** [Dobeash/Munge#1]
Using the chinook SQLite sample database from https://www.sqlitetutorial.net/,
the statement:

> SELECT city FROM customers ORDER BY city;

is expected to return 59 records, including duplicate rows.
But munge/sqlite only returns 53 records, as all duplicate rows are removed.
This is not supposed to happen.

Setting **denull** to true or false does not make a difference

[04_distinct.txt](https://github.com/Dobeash/Munge/files/11132652/04_distinct.txt)

**Comment by fvanzeveren** [comment]
Further weird behaviour with DISTINCT, always with the same sample database.

> SELECT city, country
> FROM customers 
> ORDER BY country

returns 59 records with sqlite3.
ctx-munge/sqlite only returns 55 records, removing **some** duplicate values.

Finally, ctx-munge/sqlite returns only 53 records when executing

>  SELECT city, country
> FROM customers
> ORDER BY country, city;

**Comment by Dobeash** [comment]
The `sqlite` and `sqlcmd` functions return a tab-delimited string which is passed to `load-dsv`. `load-dsv` discards rows that only contain blank values or are identical to the last parsed row. It also trims each cell value.

Also note that `settings/denull` defaults to true and clears returned `NULL` and `null` values.

**Comment by fvanzeveren** [comment]
Thank you, so my understanding of the script was wrong.

Regards
